#---------------------------------------------------------------------------#
# Environmental variables                                                   #
#---------------------------------------------------------------------------#

  # Java -------------------------------------------------------------------#
    export JAVA_8="C:\Program Files\Java\jdk1.8.0_25"
    export JAVA_7="C:\Program Files\Java\jdk1.7.0_21"
    export JAVA_HOME=$JAVA_8

    

  # Maven ------------------------------------------------------------------#
    export M3_HOME="C:\Program Files\apache-maven-3.2.5"
    export MAVEN_HOME=$M3_HOME
    
  # Sublime Text -----------------------------------------------------------#
    export SUBLIME_HOME="C:\Program Files\Sublime Text 3"

  # Path -------------------------------------------------------------------#
    export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$SUBLIME_HOME:$PATH


#---------------------------------------------------------------------------#
# Git shortcuts                                                             #
#---------------------------------------------------------------------------#
   
  alias fetch="git fetch"
  alias merge="git merge"
  alias add="git add"
  alias commit="git commit"
  alias status="git status"
  alias push="git push"
  alias diff="git diff"
  alias checkout="git checkout"

#---------------------------------------------------------------------------#
# Maven shortcuts                                                           #
#---------------------------------------------------------------------------#

  alias test="mvn clean test"
  alias assembly="mvn clean -U assembly:assembly"
  alias getSources="mvn dependency:sources"
  alias install="mvn clean source:jar install"


#---------------------------------------------------------------------------#
# Java shortcuts                                                            #
#---------------------------------------------------------------------------#

  alias useJava8="export JAVA_HOME=\"$JAVA_8\""
  alias useJava7="export JAVA_HOME=\"$JAVA_7\""

#---------------------------------------------------------------------------#
# More shortcuts                                                            #
#---------------------------------------------------------------------------#

  alias edit="sublime_text.exe"

#---------------------------------------------------------------------------#
# Directory Surfing                                                         #
#---------------------------------------------------------------------------#
  alias ..="cd .."
  alias ...="cd ../.."
  alias ....="cd ../../.."
  alias .....="cd ../../../.."
  